
//à»â∫ÇÃÇQÇ¬ÇÕà¯êîÇ≈éwíË
int straightcost[30];
int slalomcost[30];
int turn180cost;
int DEVIDE_START_TOSTART,DEVIDE_END_TOSTART,TRIAL_TOSTART,REVERSE_TOSTART;
int DEVIDE_START_TOGOAL,DEVIDE_END_TOGOAL,TRIAL_TOGOAL,REVERSE_TOGOAL;
int LOOKBACK_LIMITSIZE,LOOKBACK_LIMITDISTANCE,GOGOAL_LIMIT,PERMISSIBLE_RANGE;
//Ç¬Ç‹ÇËÅAbad1 < bad2

const int GOALS[]={ 6, 14, 6, 16, 8, 14, 8, 16, 7, 13, 8, 13, 7, 17, 8, 17, -1 };
